# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: space.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='space.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0bspace.proto\"0\n\x0bScoreUpdate\x12\x11\n\tastronaut\x18\x01 \x02(\x05\x12\x0e\n\x06points\x18\x02 \x02(\x05'
)




_SCOREUPDATE = _descriptor.Descriptor(
  name='ScoreUpdate',
  full_name='ScoreUpdate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='astronaut', full_name='ScoreUpdate.astronaut', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='points', full_name='ScoreUpdate.points', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=15,
  serialized_end=63,
)

DESCRIPTOR.message_types_by_name['ScoreUpdate'] = _SCOREUPDATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ScoreUpdate = _reflection.GeneratedProtocolMessageType('ScoreUpdate', (_message.Message,), {
  'DESCRIPTOR' : _SCOREUPDATE,
  '__module__' : 'space_pb2'
  # @@protoc_insertion_point(class_scope:ScoreUpdate)
  })
_sym_db.RegisterMessage(ScoreUpdate)


# @@protoc_insertion_point(module_scope)
